# Avoid Error response from daemon: client is newer than server
# (client API version: 1.23, server API version: 1.22) error.
# TODO figure out what this means and how to fix it.
FROM docker:1.10-git

# See https://github.com/bibinwilson/jenkins-docker-slave/blob/master/Dockerfile
# See http://devopscube.com/docker-containers-as-build-slaves-jenkins/
# Add user jenkins to the image
RUN adduser --quiet jenkins
# Set password for the jenkins user (you may want to alter this).
RUN echo "jenkins:jenkins" | chpasswd

RUN mkdir /home/jenkins/.m2

ADD settings.xml /home/jenkins/.m2/

RUN chown -R jenkins:jenkins /home/jenkins/.m2/

RUN apt-get install -y maven
# Standard SSH port
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
