# This is where we define how to set up a complete environment with
# our container(s).
version: '3'

volumes:
  jenkins:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - jenkins:/var/jenkins_home
      - ./docker-resources:/scripts
    working_dir: /var/jenkins_home
    restart: always
