# Avoid Error response from daemon: client is newer than server
# (client API version: 1.23, server API version: 1.22) error.
# TODO figure out what this means and how to fix it.
FROM docker:1.10-git

RUN adduser -h /home/jenkins -s /bin/sh jenkins -D
RUN echo jenkins:jenkins|chpasswd

# add openssh and clean
RUN apk add --update openssh \
&& rm  -rf /tmp/* /var/cache/apk/*
# add entrypoint script
ADD docker-resources/Dockerfile-jenkinsslave/docker-entrypoint.sh /usr/sbin

EXPOSE 22
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/usr/sbin/sshd","-D"]
